#!/bin/bash 

# MIT License
#
# (C) Copyright [2020] Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

unset LB_TEST_MODE

export \
UAS_PASSWD="hal:x:9000:9001:Hal Algo:/users/hal:/bin/bash" \
UAS_GROUPS="sshd systemd-journal" \
UAS_PUBKEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDhetalxeOvuQVlM2MmCVIqro8Z/TX1X503hGL/doSyt5LTN5C9RIbCmk+ZBZmqE4pEGPzhYTj8s9pUhe5ZIMkN6fb6ju+3Svsq9cyHkLnNrX+I49seaaGLbQ5eAw6Kfm1YrcwZi2UeULj902NodXc34ITh/qN+9MiFJ6ljnqjP2H+vrhP3C9aCHkDD45AQEeQXCXbFkfwyKRVTEvIDapd+sEs2fp8myrvm2N3oRw+9SgPJa4/GvK7tBcRDNVJk/h+Yr2Dc/lCBz9lJWDeiI6AwilgmCbK//usqoa4770o0UpZdG6q74RX3BDu63AOfxB83GExX1FkQU/GUi5AjL3h3 hal@localhost" \
UAS_NAME="hal-image" \
HAL_IMAGE_SERVICE_PORT=30124
